apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-goserver.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-goserver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-goserver.name" . }}
    spec:
      containers:
      - name: simple-goserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}